#pragma once

namespace Game
{
	enum class GLEnableCaps
	{
		BLEND,
		CLIP_DISTANCE,
		COLOR_LOGIC_OP,
		CULL_FACE,
		DEBUG_OUTPUT,
		DEBUG_OUTPUT_SYNCHRONOUS,
		DEPTH_CLAMP,
		DEPTH_TEST,
		DITHER,
		FRAMEBUFFER_SRGB,
		LINE_SMOOTH,
		MULTISAMPLE,
		POLYGON_OFFSET_FILL,
		POLYGON_OFFSET_LINE,
		POLYGON_OFFSET_POINT,
		POLYGON_SMOOTH,
		PRIMITIVE_RESTART,
		PRIMITIVE_RESTART_FIXED_INDEX,
		RASTERIZER_DISCARD,
		SAMPLE_ALPHA_TO_COVERAGE,
		SAMPLE_ALPHA_TO_ONE,
		SAMPLE_COVERAGE,
		SAMPLE_SHADING,
		SAMPLE_MASK,
		SCISSOR_TEST,
		STENCIL_TEST,
		TEXTURE_CUBE_MAP_SEAMLESS,
		PROGRAM_POINT_SIZE,
	};

	class GLEnable
	{
	public:
		static unsigned int GetGlEnableCaps(GLEnableCaps cap);
	};
}
